# permissions for end users to view inventoryclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: inventorycluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: inventory-cluster
    app.kubernetes.io/part-of: inventory-cluster
    app.kubernetes.io/managed-by: kustomize
  name: inventorycluster-viewer-role
rules:
- apiGroups:
  - multicluster.x-k8s.io.multicluster.x-k8s.io
  resources:
  - inventoryclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multicluster.x-k8s.io.multicluster.x-k8s.io
  resources:
  - inventoryclusters/status
  verbs:
  - get
